### ISSUE TITLE
Exclude test files in a monorepo structure by default

### ISSUE THREAD

**Issue by mojavelinux** [istanbuljs/istanbuljs#132]
## Expected Behavior

Test files inside packages in a monorepo structure should be ignored by default. The exclude pattern should be augmented to include the following pattern:

```
packages/*/test/**
```

An alternative would be to support a hyphenated test extension (core-test.js) in addition to the dot test extension (core.test.js).

```
**/*{.,-}test.js
```

(we could also consider adding "spec" in addition to "test" in this pattern, which is often used as well).

## Observed Behavior

Test files inside packages in a monorepo structure are being included in coverage reports.

## Forensic Information

**Operating System:** Fedora 26
**Environment Information:** nyc 11.4.1

**Comment by mojavelinux** [comment]
I think we could add both patterns. The second pattern alone would still miss utility scripts inside the test folder.

**Comment by JaKXz** [comment]
This looks like a reasonable addition to the test-exclude package IMO :)

**Comment by amb26** [comment]
Another popular monorepo pattern names this internal directory as "node_modules" rather than "packages". See this posting from the PouchDB team which refers to the "alle proposal": https://gist.github.com/nolanlawson/457cdb309c9ec5b39f0d420266a9faa4 . Unfortunately the current hardwired behaviour in test-excludes at https://github.com/istanbuljs/istanbuljs/blob/master/packages/test-exclude/index.js#L35 makes it impossible to work with this pattern since "**/node_modules/**", an overgenerous regex, always ends up in excludes whether you write it or not.

**Comment by bcoe** [comment]
@mojavelinux can we close this issue now?

**Comment by amb26** [comment]
The commit on 7th Jan doesn't resolve the problem I reported. Would you prefer me to file it as a separate issue?

**Comment by bcoe** [comment]
@amb26 yes please 👍 let's open up an issue specifically related to this other case. I'll close this, and @mojavelinux can reopen if he still feels there are some issues to address.

**Comment by mojavelinux** [comment]
I didn't have anything else to add to the request.

**Comment by mojavelinux** [comment]
> Another popular monorepo pattern names this internal directory as "node_modules" rather than "packages". 

I think this is a tremendously bad idea. The directory name node_modules has an extremely well-defined meaning in Node, so much so that it can't even be renamed. To use that name for any another purpose would confuse many tools that are well rooted in the conventional meaning. I think it would be a mistake for istanbul to cater to what the PouchDB team is doing.

**Comment by amb26** [comment]
I will file a separate issue - but just to respond to mojavelinux's remarks - if you read the well-thought-out "alle proposal" that I link in the first gist above, you will find that it is precisely because of the well-defined meaning of node_modules that this name is chosen. PouchDB is a major, long-running and well-attested project in the node.js ecosystem, and they didn't adopt their layout idly, but after years of gathering experience with the "lerna" monorepo layout and finding that it didn't work for them.

**Comment by mojavelinux** [comment]
I've read it and I still disagree. It's exploiting the resolution algorithm for a different purpose. But we don't have to agree, because this isn't my battle to win.
