### ISSUE TITLE
Cannot read property 'some' of undefined after upgrade to latest version

### ISSUE THREAD

**Issue by jannakha** [istanbuljs/istanbuljs#145]
my jest tests started failing after latest version:

TypeError: /home/rof/src/github.com/uqlibrary/fez-frontend/src/modules/SharedComponents/PublicationCitation/components/citations/ManuscriptCitation.js: Cannot read property 'some' of undefined
at VisitState.onEnter (node_modules/istanbul-lib-instrument/dist/visitor.js:147:65)
at VisitState.wrappedEntry (node_modules/istanbul-lib-instrument/dist/visitor.js:336:14)
at NodePath._call (node_modules/babel-traverse/lib/path/context.js:76:18)
at NodePath.call (node_modules/babel-traverse/lib/path/context.js:48:17)
at NodePath.visit (node_modules/babel-traverse/lib/path/context.js:105:12)
at TraversalContext.visitQueue (node_modules/babel-traverse/lib/context.js:150:16)
at TraversalContext.visitMultiple (node_modules/babel-traverse/lib/context.js:103:17)
at TraversalContext.visit (node_modules/babel-traverse/lib/context.js:190:19)
at Function.traverse.node (node_modules/babel-traverse/lib/index.js:114:17)
at NodePath.visit (node_modules/babel-traverse/lib/path/context.js:115:19)

Possible issue here:
https://github.com/istanbuljs/istanbuljs/blame/master/packages/istanbul-lib-instrument/src/visitor.js#L106

any suggestions on how to fix?
thanks

**Comment by jannakha** [comment]
npm vs yarn issue

**Comment by eMerzh** [comment]
@jannakha , also using yarn, any tip how you managed to fix it ?

**Comment by BabakMN** [comment]
I can confirm that the issue is present in **v1.10.0**.

For those who are using yarn here's a **temporary fix**.

Add this to your own `package.json`:

```json
"resolutions": {
    "**/istanbul-lib-instrument": "1.9.2"
},
```

Thanks to yarn's [selective dependency resolution feature](https://yarnpkg.com/lang/en/docs/selective-version-resolutions/).

This will pin `istanbul-lib-instrument` to **v1.9.2** (which works) until a patch is released. :+1:

**Comment by chrisjlee** [comment]
If you're using npm. Is there a solution for that?

**Comment by bradzacher** [comment]
this issue should be reopened as it's not fixed.
It's not an issue with yarn vs npm - it's a bug in the latest release.

I ran through a debugger and it's a problem with how the default arguments have been used.

`programVisitor` has default value for `opts` set to `defaultProgramVisitorOpts`.
https://github.com/istanbuljs/istanbuljs/blob/4207dc6104ef3eb924a91ec44ef8f42d4db92169/packages/istanbul-lib-instrument/src/visitor.js#L533

This works - if the caller passes no value for opts at all.
However if the caller passes an object which is missing any of the options (say, `ignoreClassMethods`), then it will not be set, as that's not how default values work.

This is what is triggering the bug.
In my debug session at least, `babel-plugin-istanbul` calls `programVisitor` passing an opts argument *without* the `ignoreClassMethods` option.
https://github.com/istanbuljs/babel-plugin-istanbul/blob/18fe954688fb4b9450138bf6f471446a88573133/src/index.js#L67

because it's not provided, it's of course `undefined`.

Within the `VisitState` constructor, it assumes everything is in order, and stores `undefined` against its class property.
https://github.com/istanbuljs/istanbuljs/blob/4207dc6104ef3eb924a91ec44ef8f42d4db92169/packages/istanbul-lib-instrument/src/visitor.js#L23-L35

The fix is pretty simple - provide default values for the arguments to the `VisitState` constructor

**Comment by bcoe** [comment]
@eMerzh  @jannakha this should be fixed now, thanks to @bradzacher's patch; let me know if you continue to bump into any issues.
