### ISSUE TITLE
Adopt caching-transform?

### ISSUE THREAD

**Issue by novemberborn** [istanbuljs/istanbuljs#183]
We've stopped using https://github.com/avajs/caching-transform in AVA. As it's still used in nyc, perhaps it makes sense to move the repository to this organization? I think I can still do all that on my end, and then leave it up to folks here whether it should go into this monorepo or can remain its own repository.

**Comment by coreyfarrell** [comment]
New member speaking here but I have no objection to adopting this module.  It appears to be very low maintenance and if needed I could take lead, though I do prefer the git repo be under istanbuljs.

My vote is to keep it in a separate repository rather than merging into the monorepo.  caching-transform and the monorepo don't depend on each other.  Putting it in the monorepo won't improve testing so I'd prefer to keep the unmodified commit/tag history.

**Comment by novemberborn** [comment]
Thanks @JaKXz. I’ve moved it over.
