### ISSUE TITLE
bug: istanbul-lib-instrument@2.x should not use beta babel 7 packages

### ISSUE THREAD

**Issue by hulkish** [istanbuljs/istanbuljs#206]
If beta babel 7 packages are being introduced - it should occur on a new major release of `istanbul-lib-instrument`. Releasing these as a patch has to be a mistake?

**Comment by coreyfarrell** [comment]
Babel 7 upgrade is the initial reason istanbul-lib-instrument was bumped to 2.0.0.

See [istanbul-lib-instrument@2.0.0](https://github.com/istanbuljs/istanbuljs/commits/istanbul-lib-instrument%402.0.0) commit log.

**Comment by hulkish** [comment]
I see, i think my mistake was upgrading `nyc`, then - where these changes were picked up.

**Comment by coreyfarrell** [comment]
nyc 12.x uses babel 6 (current latest nyc), nyc 13.x uses babel 7 (currently next).  nyc 13.x and istanbul-lib-instrument 2.x will be released as `latest` soon.  Also note that semver is only honoured for releases to `latest`, if we release 2.0.1 to `next` only then 2.0.2 could contain a breaking change.  I plan to look into modifying the process so that we use semver beta versions during the `next` phase of major releases but I don't have an ETA for that.

I'm closing this ticket since as far as I can tell the upgrade to babel 7 is being done correctly.  If you have further concerns feel free to comment or join us at the #istanbuljs channel on slack http://devtoolscommunity.herokuapp.com/
