### ISSUE TITLE
Exception while collecting coverage metrics

### ISSUE THREAD

**Issue by holgergp** [istanbuljs/istanbuljs#207]
Hi,

I am encountering a crash of `nyc` when collecting code coverage (looking at coverage from Jest and Cucumberjs) when executing `$ nyc report --reporter=lcov`
I am using  `"nyc": "12.0.2",`
The following exception is raised
```
TypeError: Cannot read property 'decl' of undefined
    at /myProject/node_modules/nyc/node_modules/istanbul-reports/lib/lcovonly/index.js:32:38
    at Array.forEach (<anonymous>)
    at LcovOnlyReport.onDetail (/myProject/node_modules/nyc/node_modules/istanbul-reports/lib/lcovonly/index.js:30:28)
...
```
This only occurs when executing this in an Gitlab CI environment based on an node:8 Docker image.
If I run this locally everything is fine.
I doublechecked the [source](https://github.com/istanbuljs/istanbuljs/blob/master/packages/istanbul-reports/lib/lcovonly/index.js#L32) mentioned in the stacktrace, but I am afraid I cannot get my head around it: Somehow the `meta` object is undefined where it shouldn't be.

Any idea what I could be doing wrong here?
Thanks for your help!

**Comment by mindriven** [comment]
same here

**Comment by ReuDa** [comment]
+1 :-(

**Comment by sveg-pl** [comment]
Hi Guys,

I stumbled across this error in my project last week. What is interesting, is the intermittent nature of this issue - it affected my copy of the code base and some other guys' in my team, yet there were people not experiencing this bug at all. Moreover, when I purged all node_modules directories, all lock files, build and coverage folders, after ```npm i``` the bug was still present. However, when the project was cloned to a new directory the coverage report was generated without any problems...

These are my observations:
- it's connected to the lcov report type, so when I changed it to 'text', everything was working well;
- this variable which is undefined when istanbul is trying to read the ```decl``` property is related to the number of function's hits in a certain test file. When this number is 0 (so no code was covered in the whole file), we are getting ```undefined```.

So why no functions were hit by coverage? In my case, it was caused by an ES6 arrow notation of function in the file's export. It was basically something like:
```
export default prop => (/*some expression using the prop*/)
```
when I changed it to the ```export default function (prop) { return (/*code*/) }``` the coverage was being counted properly.

Temporary solutions I tried:
- exclude test file(s) which are causing this issue in jest's ```collectCoverageFrom``` option (our project is based on create-react-app);
- change the arrow notation in export.

Hope it helps.

**Comment by holgergp** [comment]
Thanks for your hints and sorry for not answering for quite some time.

In the light of the new version of nyc, I gave another shot at fixing that crash. 

Things I tried in the meantime, that were unsuccessful:
- pinpoint a single test as culprit, 
- different report types made no difference, 
- the `--all` option

While the new version did not solve our issue, I dug into the docs of [Babel-Plugin-Istanbul](https://github.com/istanbuljs/nyc#use-with-babel-plugin-istanbul-for-babel-support) and this seemed to do the trick.

Until the point nyc stopped working in our setup, we didn't need to bybass Babel instrumentation in the context of istanbul. Now that seems to be necessary. 
I added` babel-register` and introduced a `.nycrc`: 
```
{
    "require": ["babel-register"],
    "sourceMap": false,
    "instrument": false
}
```
Now the coverage generation works again!

Your temporary solution of using ES5 functions instead of arrow functions, may point in that direction as well. How do you deal with babel instrumentation?

**Comment by holgergp** [comment]
Closing as it works for me now.

**Comment by alexandermckay** [comment]
Coming to this in 2020: 

```json
{
  "require": ["@babel/register"]
}
```
