### ISSUE TITLE
[Question] Istanbul-api published with next tag

### ISSUE THREAD

**Issue by Sibiraj-S** [istanbuljs/istanbuljs#209]
Is there a reason why `istanbul-api` v2.x is published with `next` tag. and the latest version still points to 1.x?

2.x already got 5 pathes I guess.

**Comment by coreyfarrell** [comment]
The istanbul and nyc modules take a conservative approach to releasing.  Everything from `next` will be tagged `latest` soon (probably early next week if no regressions are uncovered).  I've called for testing at istanbuljs/nyc#902.

We've been a bit slower than normal to release 2.x because it upgrades from babel 6 to babel 7.
