### ISSUE TITLE
istanbul-api upgrades istanbul-lib-instrument from 1 to v2 in a minor version

### ISSUE THREAD

**Issue by ljharb** [istanbuljs/istanbuljs#216]
v2.3.2 of `istanbul-lib-instrument` includes untranspiled arrow functions, which is a breaking change.

This is currently blocking an important feature in enzyme; it'd be great to publish a v2.3.3 that fixes this ASAP.

**Comment by coreyfarrell** [comment]
This was the original reason for the semver-major from 1.x to 2.x, babel 7 requires node 6. See the [CHANGELOG.md](https://github.com/istanbuljs/istanbuljs/blob/master/packages/istanbul-lib-instrument/CHANGELOG.md#200-2018-05-31).

I'm not sure how to resolve this issue, if you don't mind me asking what are you trying to do that cannot be done with istanbul-lib-instrument@1?

**Comment by ljharb** [comment]
hmm - i only actually depend on `^1.0.0-alpha.2` - and builds very suddenly started failing on node 4.

Is it possible that there's something in the dependency tree that doesn't use `^`?

**Comment by ljharb** [comment]
Looks like the bug is in istanbul-api: https://unpkg.com/istanbul-api@1.3.6/package.json uses istanbul-lib-instrument v2, but https://unpkg.com/istanbul-api@1.2.2/package.json uses v1, and that's a breaking change in a minor version.

Could you publish a v1.3.7 that drops istanbul-lib-instrument back down to v1?

**Comment by ljharb** [comment]
(i'm assuming istanbul-api@1.3 was very recently changed from "next" to "latest", and that's why i'm seeing this in the last 24-48 hours?)

**Comment by coreyfarrell** [comment]
Odd I thought that v1.2.2 was the last version published to latest.  I guess when I published v2 to latest it also published all v1.3.x to latest as well.  I'll work on republishing v1.2.2 as v1.4.0.

**Comment by ljharb** [comment]
Thanks!

**Comment by coreyfarrell** [comment]
@ljharb I believe this should be resolved, could you test again with istanbul-api unpinned?

**Comment by ljharb** [comment]
Thanks, that resolves the issue!

**Comment by bryanforbes** [comment]
For next time, when publishing breaking changes, please bump all of the minor versions. `istanbul-lib-coverage` version `1.2.0` had `CoverageSummary.prototype.isEmpty` and version `1.2.1` no longer has this method. Intern had `istanbul-reports` set to `~1.3.0` (which used the `isEmpty()` method, evidently accidentally) and `istanbul-lib-coverage` set to `~1.2.0` and all of Dojo's CI began to break yesterday because of the API removal on a micro version. This wouldn't have happened had `istanbul-lib-coverage` version `1.2.1` been published on version `1.3.0`.

**Comment by coreyfarrell** [comment]
@bryanforbes I'm sorry for the trouble you are having, unfortunately I have limited bandwidth.  #217 was posted for 9 days and nobody raised concerns.  I understand that without monitoring this repository you could not have known what I was going to do before it was merged and released, the problem is not many others actively monitor this repository.  Obviously the hope is that we'll avoid improper breaking change release in the future but mistakes happen.

As for dealing with Dojo if you are using babel 7 then I recommend using npm's `next` versions of istanbul modules (latest uses babel-7.0.0-beta.51, next was updated last night to use ^7.0.0).  If you are still using babel 6 then it might be best to pin things to specific versions of 1.x.  I do not plan to make any further releases to the 1.x versions, I'm not confident that I could do anything that would not break things for someone (my limited time is also a factor).

**Comment by bryanforbes** [comment]
I understand it wasn't a great situation and I completely understand having limited bandwidth. I apologize if I came across as wanting a pound of flesh. I was only attempting to raise awareness for the future.

**Comment by coreyfarrell** [comment]
No it makes sense and I appreciate the idea - IMO you did not come across as attacking.  If something like this ever happens again (hopefully not) I will make a point to mark the revert patch as a feature so that our release process creates a semver-minor release instead of semver-patch.

Honestly I suspected that something like this would happen but didn't see a way around it.  Ultimately I wanted to get the reverted release out sooner than later in the hope that less people would update to the improperly released versions.
