### ISSUE TITLE
Feature Request: Ability to increase width of 'Uncovered Lines' in text report.

### ISSUE THREAD

**Issue by DrMiaow** [istanbuljs/istanbuljs#227]
Would make this easier to work with.
Also, the ability to list uncovered lines from start, not from the end.

**Comment by papb** [comment]
Listing uncovered lines from the start would be great indeed!

**Comment by coreyfarrell** [comment]
nyc@15 will produce a much wider `Uncovered Lines` column, fixed in #341.

With regard to printing from the start that is something that was considered and decided against.  See https://github.com/istanbuljs/istanbuljs/pull/341#issuecomment-494786889 - short reason if you are fixing a file you should start from the end, that way inserting an `/* istanbul ignore next */` or making other changes does not invalidate all other line numbers reported.
