### ISSUE TITLE
Issue with istanbul-lib-source-maps

### ISSUE THREAD

**Issue by coreyfarrell** [istanbuljs/istanbuljs#231]
jest is being upgraded to babel 7 and latest istanbul modules.  An error was found in the coverage report for a file, the first statement / line of the source file is lost.  This loss occurs when the coverage data is processed by istanbul-lib-source-maps:
https://github.com/facebook/jest/blob/9d5ead81bd5ad067544da8fc655f672a232445ff/packages/jest-cli/src/reporters/coverage_reporter.js#L86-L88

See also facebook/jest#7202

**Comment by TakuyaHara** [comment]
In my case when using TypeScript@3.2.2 + Babel 7, I used `ts-jest` to solve. I wrote a detail here.
https://medium.com/@TakuyaHARA/need-ts-jest-when-using-typescript-babel-7-jest-fc077ae32e2d

While I'm in a middle I also investegated this issue and let me share the result at this moment.

# Why I get wrong coverage?
[this._sourceMapStore.transformCoverage](https://github.com/facebook/jest/blob/9d5ead81bd5ad067544da8fc655f672a232445ff/packages/jest-cli/src/reporters/coverage_reporter.js#L86-L88) calls `MapStore.prototype.transformCoverage` but [transform](https://github.com/istanbuljs/istanbuljs/blob/master/packages/istanbul-lib-source-maps/lib/map-store.js#L120) will not be performed because `this.data` is `{}` at [L144](https://github.com/istanbuljs/istanbuljs/blob/master/packages/istanbul-lib-source-maps/lib/map-store.js#L114). 

# Why `this.data` is `{}`?
`this.data` would be added at [MapStore.prototype.registerURL](https://github.com/istanbuljs/istanbuljs/blob/master/packages/istanbul-lib-source-maps/lib/map-store.js#L44) or [MapStore.prototype.registerMap](https://github.com/istanbuljs/istanbuljs/blob/master/packages/istanbul-lib-source-maps/lib/map-store.js#L74). They may be called from CoverageReporter's `onTestResult` but actually they are never called because `testResult.sourceMaps` is `{}` at [L60](https://github.com/facebook/jest/blob/9d5ead81bd5ad067544da8fc655f672a232445ff/packages/jest-cli/src/reporters/coverage_reporter.js#L60).

# Why `testResult.sourceMaps` is `{}`?
`testResult.sourceMaps` will be assigned `runtime.getSourceMapInfo`'s returned value at [L206](https://github.com/facebook/jest/blob/9d5ead81bd5ad067544da8fc655f672a232445ff/packages/jest-runner/src/run_test.js#L206) but as `this._needsCoverageMapped` is `{}` at [L474](https://github.com/facebook/jest/blob/9d5ead81bd5ad067544da8fc655f672a232445ff/packages/jest-runtime/src/index.js#L474) if clause's condition is always false. Then it returns `{}`.

# Why `this._needsCoverageMapped` is `{}`?
`this._needsCoverageMapped` would be added by `this._needsCoverageMapped.add` in Runtime's `_execModule` but actually it is unreachable because `transformedFile.mapCoverage` is `false` at [L627](https://github.com/facebook/jest/blob/9d5ead81bd5ad067544da8fc655f672a232445ff/packages/jest-runtime/src/index.js#L629).

# Why `transformedFile.mapCoverage` is `false`?
`transformedFile.sourceMapPath` will be assigned `this._scriptTransformer.transform` at [L616](https://github.com/facebook/jest/blob/9d5ead81bd5ad067544da8fc655f672a232445ff/packages/jest-runtime/src/index.js#L616). When Runtime's `_transformAndBuildScript` is called, `mapCoverage` that returns at [L325][https://github.com/facebook/jest/blob/9d5ead81bd5ad067544da8fc655f672a232445ff/packages/jest-runtime/src/script_transformer.js#L331) will be assigned by `transformedSource.mapCoverage` at [L325](https://github.com/facebook/jest/blob/9d5ead81bd5ad067544da8fc655f672a232445ff/packages/jest-runtime/src/script_transformer.js#L325). This is `false`.

# Why `transformedSource.mapCoverage` is `false`?
`transformedSource.mapCoverage` will be assigned `this.transformSource` at [L317](https://github.com/facebook/jest/blob/9d5ead81bd5ad067544da8fc655f672a232445ff/packages/jest-runtime/src/script_transformer.js#L317). `mapCoverage` that returns at [L289](https://github.com/facebook/jest/blob/9d5ead81bd5ad067544da8fc655f672a232445ff/packages/jest-runtime/src/script_transformer.js#L289) will be assigned `false` at [L223](https://github.com/facebook/jest/blob/9d5ead81bd5ad067544da8fc655f672a232445ff/packages/jest-runtime/src/script_transformer.js#L223).

# Why `mapCoverage` is `false`?
`transformWillInstrument` is `true` because `transform.canInstrument` at [L219](https://github.com/facebook/jest/blob/9d5ead81bd5ad067544da8fc655f672a232445ff/packages/jest-runtime/src/script_transformer.js#L219) is `true`.

# Why `transform.canInstrument` is `true`?
Because it is defined in babel-jest at [L49](https://github.com/facebook/jest/blob/1818d84b2cf20ecb8db2215b3ad6b5e397ab2673/packages/babel-jest/src/index.js#L49)

# What happens if I set `transform.canInstrument` to `false`?
`this.data` contains source maps at [L144](https://github.com/istanbuljs/istanbuljs/blob/master/packages/istanbul-lib-source-maps/lib/map-store.js#L114), then [transform](https://github.com/istanbuljs/istanbuljs/blob/master/packages/istanbul-lib-source-maps/lib/map-store.js#L120) will be performed but you still get incorrectly mapped coverage. It is source-map used by istanbul-lib-source-maps which tries to find an index to return a mapped position at [L604](https://github.com/mozilla/source-map/blob/0.5.7/lib/source-map-consumer.js#L604). You see that `this._generatedMappings` refers wrong position of TS code.

# Why `this._generatedMappings` refers wrong position?
Sorry, let me have a break here 😵. I hope this is helpful 👍.

**Comment by SimenB** [comment]
This has been fixed in https://github.com/istanbuljs/istanbuljs/pull/255

**Comment by coreyfarrell** [comment]
@takuyahara We've had a couple fixes to source map handling, can you recheck against latest versions let us know if this is still an issue?

**Comment by coreyfarrell** [comment]
To my knowledge this issue is fixed.  I'm closing this issue since we have not received any recent response or report.
