### ISSUE TITLE
vulnerability in handlebars under istanbul-reports

### ISSUE THREAD

**Issue by em0ney** [istanbuljs/istanbuljs#366]
Hi there,

There is a high severity prototype pollution vulnerability in the handlebars version being used within istanbul-reports.

```
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ handlebars                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=4.0.14 <4.1.0 || >=4.1.2                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ nyc [dev]                                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ nyc > istanbul-reports > handlebars                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/755                             │
└───────────────┴──────────────────────────────────────────────────────────────┘
found 1 high severity vulnerability in 8708 scanned packages
  1 vulnerability requires manual review. See the full report for details.
```

**Comment by jamiemjennings** [comment]
@coreyfarrell @JaKXz: this is causing major pain for anyone that relies on `npm audit` in CI to block builds with vulnerabilities. I opened https://github.com/istanbuljs/istanbuljs/pull/365 hoping this could offer a quick low-risk fix for the `npm audit` reported vulnerability but that's since been closed. [Comments](https://github.com/istanbuljs/istanbuljs/pull/362#issuecomment-483445218) on https://github.com/istanbuljs/istanbuljs/pull/362 suggest it might not even get fixed - even with a `package.json` semver a PR is still needed to update `package-lock.json`.

For those of us with our builds currently blocked by this `npm audit` report, is there any hope of getting a new `nyc` build with the updated handlebars dependency `>=4.1.2` soon? Thanks

**Comment by em0ney** [comment]
@jamiemjennings  I was just about to open a PR of my own - nice job.

Pity, it seems that there is no interest in getting this fixed soon based on those comments you directed me to. @coreyfarrell - false positive or not, this is breaking builds for a lot of istanbul/nyc users. Can we please just get this version bump released while we wait for nyc@14?

**Comment by em0ney** [comment]
In the short term, I may just install `nyc@14.0.0-rc.1` just to get this unblocked

**Comment by coreyfarrell** [comment]
nyc@14.0.0 is now released which clears the `npm audit` report.  Moving forward this will be less likely to be an issue as we're no longer bundling dependencies into nyc, this bundling effectively pinned all dependencies to whatever was available at the time of nyc's `npm publish`.  The 4 PR's we received to this repo would not have accomplished anything without a new release of nyc which we were already working on.

Regarding blocked CI builds: you chose to add `npm audit` to the checks.  I recommend using a separate service such as snyk.io but if you choose to use `npm audit` to block CI then you will have to deal with the consequences of that from time to time.  IF this were a vulnerability that actually effected nyc / istanbuljs then we'd find a way to make it a priority but that's simply not the case with this handlebars vulnerability.

I realize my comments are not what the reporter / commenters want to hear and I'm sorry but this is the reality of our ability to provide support.  Please do not forget that nyc / istanbuljs are not products, they are open source projects maintained by (very few) volunteers.

**Comment by jamiemjennings** [comment]
@coreyfarrell: It wasn't obvious that nyc v14 was hours away from being released from earlier comments. The nyc v14 release fixed the issue so thanks for that! Indeed I understand the challenge of open source projects which is why I try to help out whenever possible - such as opening that PR that was closed. Thanks for your efforts!
