### ISSUE TITLE
Per-test coverage information

### ISSUE THREAD

**Issue by jbloxham** [istanbuljs/istanbuljs#462]
I'm hoping to use Istanbul to get per-test coverage information on my files, so I can cross-reference this with a list of changed files to, for instance, truncate the set of tests that need to be ran. It would be great if there were a way to use Istanbul to get this information.

**Comment by coreyfarrell** [comment]
nyc does not have a concept of individual tests.  It does know about processes, but these processes are opaque to nyc.  I suggest taking a look at coverage maps in tap - https://node-tap.org/docs/coverage/coverage-map/.  nyc exposes has a feature to support filtering coverage per process but it is up to the testing framework to use this.  Since nyc works with any test framework I don't think further support can be added here, it would be up to the testing framework.

**Comment by coreyfarrell** [comment]
I'm closing this issue as out of scope.  nyc provides the functionality to allow test runners to implement this functionality but since istanbuljs/nyc has no concept of tests it cannot be implemented here.
