### ISSUE TITLE
Error in migration files.

### ISSUE THREAD

**Issue by tech-somish** [istanbuljs/istanbuljs#494]
Error: while migrating Migrations: Returned error: Exceeds block gas limit
    at C:\Users\PC 1\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\truffle-deployer\src\deployment.js:364:1
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
Truffle v5.0.8 (core: 5.0.8)
Node v8.11.3
Cleaning up...
Event trace could not be read.
Error: ENOENT: no such file or directory, open 'D:\Prem\HopabotContracts\allFiredEvents'
Exiting without generating coverage...

can anyone help me out with above error.

**Comment by coreyfarrell** [comment]
This does not appear to be a valid bug report against istanbul or nyc.  I'm not familiar with the `Exiting without generating coverage` error message.  I suggest running `grep -lR node_modules -e 'Exiting without generating coverage'` to determine where that error came from and post a bug report against that package.  If it is determined that this is somehow caused by one of the current istanbuljs modules please feel free to post again but include more information.
