### ISSUE TITLE
"undefined" reported in "uncovered lines"

### ISSUE THREAD

**Issue by dmitriiabramov** [istanbuljs/istanbuljs#51]
originally reported in https://github.com/facebook/jest/issues/3491

i was able to reproduce locally.
after i downgraded istanbul-api by doing `yarn add istanbul-api@1.1.0-alpha.1` the problem seemed to go away.
i wasn't able to reproduce it on other projects, just the one in the issue.
any ideas what could have caused it?

**Comment by bcoe** [comment]
@dmitriiabramov will dig into this when I have some time this week, and switch things back to the old behavior.

**Comment by bcoe** [comment]
@ZeeCoder @dmitriiabramov I can't for the life of me seem to get a reproduction -- I've checked out `greenkeeper/jest-20.0.0`, and am seeing missing branch coverage as expected.

@ZeeCoder are you still able to reproduce?

**Comment by ZeeCoder** [comment]
@bcoe I'll check it as soon as I can, thanks for looking into it :+1:

**Comment by ZeeCoder** [comment]
@bcoe yeah I can still reproduce it with Jest 20.0.3 (https://github.com/ZeeCoder/container-query/pull/31)

If you check `master`, and run yarn && yarn test, you won't see any undefined.
But if you check out `greenkeeper/jest-20.0.3`, and again run yarn && yarn test you'll see the undefined lines.

![jestundefinedcoeverage](https://cloud.githubusercontent.com/assets/3679506/26225839/123dde9a-3c21-11e7-9eb9-97908507e760.png)

**Comment by bcoe** [comment]
@ZeeCoder @dmitriiabramov aha! I believe the problem is that your yarn.lock has you pinned at incompatible versions of `istanbul-lib-report`, and `istanbul-lib-instrument` (I use npm, so wasn't immediately seeing the issue).

* If I install using your current `yarn.lock` file, I reproduce your behavior.
* If I delete the `node_modules` folder and `yarn.lock` and perform an install, the issue goes away.
* If I install with npm I also don't have an issue.

For me, things seem to work like a charm if I just remove:

```yaml
istanbul-lib-report@^1.0.0-alpha.3:
  version "1.0.0-alpha.3"
  resolved "https://registry.yarnpkg.com/istanbul-lib-report/-/istanbul-lib-report-1.0.0-alpha.3.tgz#32d5f6ec7f33ca3a602209e278b2e6ff143498af"
  dependencies:
    async "^1.4.2"
    istanbul-lib-coverage "^1.0.0-alpha"
    mkdirp "^0.5.1"
    path-parse "^1.0.5"
    rimraf "^2.4.3"
    supports-color "^3.1.2"
```

from your yarn.lock 👍 feel free to reopen if you're still bumping into this issue, but I think this slight tweak to your lock file should fix things up for you.

**Comment by ZeeCoder** [comment]
Ah, I ran `yarn upgrade` which solved my issue.
Now I got a proper report about uncovered lines. :+1: 

Thanks for looking into this. :raised_hands:
