### ISSUE TITLE
Performance of instrument between istanbul-lib-instrument and istanbul@0.x

### ISSUE THREAD

**Issue by popomore** [istanbuljs/istanbuljs#52]
I found the performance of instrument is different when I upgrade istanbul from 0.x to 1.x (and I also tried nyc which is same).

I have pushed my test code to https://github.com/popomore/istanbul-instrument, you can run `node test.js` to see the result.

istanbul@1.x and nyc are using istanbul-lib-instrument to instrument code depending on babylon, but istanbul@0.x is using esprima. Is that mean babylon is slower than esprima?

**Comment by bcoe** [comment]
@popomore I believe at the end of the day babylon is a bit slower than esprima -- but we've opted to use this approach due to the fact that it gave us a lot of flexibility, and solved many of the ES6 instrumentation issues that we were bumping into.

we've been relying on babylon for over a year now, and the codebase has come quite a way since then -- so I don't think there's any chance we'll be switching back to Esprima; I'm sure babylon would love help improving performance, and I'd definitely be interested, if benchmarked, to see where the hot spots are in this codebase.

**Comment by popomore** [comment]
Sorry, I don't mean it should switch back to esprima, I just have a question why babylon is slow, could it be faster? 

In my case, the speed will determine the result of ci, it will fail if it is slower.

**Comment by bcoe** [comment]
@popomore in the past folks have done some performance work, such as switching Istanbul to being 0 indexed rather than 1 indexed -- which significantly improves V8 performance. It would be interesting to see if there are some other wins.

It would be interesting to run with:

https://www.npmjs.com/package/v8-profiler

and see if any performance bottlenecks jump out; another thing you might try:

make sure both `--cache` and `--babel-cache` are `true` (I believe babel-cache defaults to `false)`. This should cut down on the amount of instrumentation that needs to take place.

**Comment by popomore** [comment]
I'm glad to seek the problem, but I want to ask @hzoo first.

**Comment by bcoe** [comment]
@popomore there might definitely be some wins on both the istanbuljs and babel side -- it's always fun to crack out a profiler 👍

**Comment by popomore** [comment]
```
istanbul-lib-instrument parse: 100.553ms
istanbul-lib-instrument traverse: 479.304ms
istanbul-lib-instrument gen: 197.976ms
istanbul-lib-instrument: 780.625ms
istanbul@7.x parse: 60.204ms
istanbul@7.x traverse: 46.080ms
istanbul@7.x gen: 48.241ms
istanbul@0.x: 156.004ms
```

it seems `babel-traverse` is mush slower
