### ISSUE TITLE
Security finding in istanbul-lib-report

### ISSUE THREAD

**Issue by AaronSterlingGENEICD** [istanbuljs/istanbuljs#725]
Please update the version of the make-dir library. The version istanbul-lib-report curently consumes produces a moderate security finding. 
 ```
make-dir  2.0.0 - 3.1.0
  Depends on vulnerable versions of semver
  node_modules/make-dir
    istanbul-lib-report  >=2.0.5
    Depends on vulnerable versions of make-dir
    node_modules/istanbul-lib-report
```
Link to root vulnerability: https://github.com/advisories/GHSA-c2qf-rxjj-qqgw

Thank you very much!

**Comment by abelk2** [comment]
Let me add some additional information on this.
- `make-dir@3.1.0` was confirmed to be unaffected by this vulnerability, see: https://github.com/sindresorhus/make-dir/issues/39#issuecomment-1603254995
- Another Istanbul package, `istanbul-lib-instrument@5.2.1` is also reported by audit, but also seems unaffected:
  - It depends on `@babel/core@7.x` (transitive dependency on `semver`), which is confirmed to be unaffected, see https://github.com/babel/babel/issues/15720#issuecomment-1606789221
  - It depends directly on `semver@6.3.0`, but it does not seem to use it in its code.

So we could say Istanbul is also unaffected, but an official confirmation would be appreciated.

**Comment by legendecas** [comment]
Upgrading make-dir from `^3.0.0` to `^4.0.0` breaks compatibility with Node.js v8.x as it uses [Optional catch binding](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/try...catch#browser_compatibility) syntax which is supported since Node.js v10. 

This breaks nyc's engine support declaration as `node >= 8.9`: https://github.com/istanbuljs/nyc/blob/master/package.json#L100C20-L100C20
