### ISSUE TITLE
feature request: preserve function.toString()

### ISSUE THREAD

**Issue by isaacs** [istanbuljs/istanbuljs#87]
As mentioned in [this comment](https://github.com/istanbuljs/nyc/issues/470#issuecomment-330276965), Istanbul's function munging can interfere with cases where a program is relying on function.toString().  It seems possible (in theory at least) to preserve this by capturing the `toString()` result of the original function.

Example:

```js
// t.js
const f = () => x = 100
console.log(f.toString())
```

```
$ node t.js
() => x = 100

$ nyc node t.js
()=>{cov_2bdy3zmxoh.f[0]++;cov_2bdy3zmxoh.s[1]++;return x=100;}
```

```js
// s.js
const f = () => x = 100
f.toString = () => '() => x = 100'
console.log(f.toString())
```

```
$ node s.js
() => x = 100

$ nyc node s.js
() => x = 100
```

I'm not interested in debating whether it's a _good_ idea to rely on function.toString(), but the fact is that some folks do, and istanbul breaks that use case.  Would prevent >0 issues to preserve it :)

**Comment by bcoe** [comment]
@isaacs @thetutlage rather than trying to preserve the function `toString()` during instrumentation, which I think could lead to a lot of complexity, I've been putting quite a bit of work into native test coverage in v8:

https://chromium-review.googlesource.com/c/v8/v8/+/778288/7

I think that this could be a great path forward for a less intrusive approach to test coverage.

**Comment by johnrellisroutematch** [comment]
well, figuring this out was one late night i won't forget soon!

**Comment by coreyfarrell** [comment]
I'm not sure this can be fixed in istanbul.  [c8](https://github.com/bcoe/c8/) might be a better option for coverage reporting if `Function.toString` preservation is required (keep in mind c8 is much newer than istanbul).

Another option for use within `nyc`:
```js
/* istanbul ignore next */
const f = () => x = 100
console.log(f.toString())
```

Using the `istanbul ignore next` hint before the function will cause 'equivalent' output when running the script under nyc vs not.  Keep in mind the script is still processed by babel so the exact string produced will be different, in this test `f.toString() === '()=>x=100'` when run under nyc.  Also note that this is disabling coverage checking for the function `f`, so it won't be reported as called or not.  In theory if you only need to deal with `.toString` for a few specific function it shouldn't be too hard to determine coverage based on the caller being run.  Also if `.toString` is being called to produce a script that will be sent to a remote browser for execution then you don't need/want coverage for those functions.  Multiple functions could be grouped together as well:

```js
/* istanbul ignore next */
const browserCommands = {
   f1: () => x1 = 100,
   f2: () => x2 = 100
};

console.log(browserCommands.f1.toString(), browserCommands.f2.toString())
```
In this example only the `console.log` line is instrumented.

**Comment by syukronarie** [comment]
Anybody solved this issue? please help, thanks.

**Comment by isaacs** [comment]
@syukronarie See the comments from @bcoe and @coreyfarrell.  It won't be fixed in istanbul.  Better to use C8 for coverage, if this is a problem.

I recommend closing (and locking?) this issue, so that it's clearly marked as a `WONTFIX`.

**Comment by isaacs** [comment]
Oh, I can just close it myself. 😅
